# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, documentation, user-interface ]
  pull_request:
    branches: [ master, documentation, user-interface ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - uses: actions/setup-node@v1.4.2
      with:
        node-version: v12.x
    - uses: actions/setup-haskell@v1.1
      with:
        enable-stack: true
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

      # - name: Add local bin to PATH
      # - shell: bash
      # - run: echo "##[add-path;]$(stack path --local-bin)"

    - name: Install ltext
      run: |
        cd ltext/
        stack install
        cd ../

    - name: Install graphmod
      run: |
        cd graphmod/
        stack install
        cd ../

    - name: Install graphviz
      run: |
        sudo apt update
        sudo apt install graphviz -y

    - name: Install chrome
      run: |
        sudo apt install google-chrome-stable -y

    - name: Install dependencies
      run: |
        npm install
        npm install -g purescript spago mocha chromedriver purty

    - name: Lint
      run: ./scripts/lint.sh

    - name: Build
      run: |
        ./scripts/build.sh
        ./scripts/build.sh production

    - name: Test
      run: npm test

    - name: Docs
      run: ./scripts/build_all_docs.sh

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Commit
      env:
        BRANCH: ${{ steps.extract_branch.outputs.branch }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add . -A
        git commit -m "Auto build"
        git pull origin $BRANCH

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.extract_branch.outputs.branch }}
