# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, documentation, user-interface ]
  pull_request:
    branches: [ master, documentation, user-interface ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - uses: actions/setup-node@v1.4.2
      with:
        node-version: v12.x
    - uses: actions/setup-haskell@v1.1
      with:
        enable-stack: true

    - name: Install graphviz
      run: sudo apt install graphviz -y

    - name: Add local bin to PATH
      shell: bash
      run: echo "##[add-path;]$(stack path --local-bin)"

    - name: Get ltext
      uses: actions/checkout@v2
      with:
        repository: ltext/ltext
        path: ltext

    - name: Install ltext
      run: |
        cd ltext/
        stack install
        cd ../

    - name: Get graphmod
      uses: actions/checkout@v2
      with:
        repository: athanclark/graphmod
        path: graphmod

    - name: Install graphmod
      run: |
        cd graphmod/
        stack install
        cd ../

    - name: Get OpenChronology
      uses: actions/checkout@v2
      with:
        repository: openchronology/openchronology.github.io
        path: openchronology.github.io

    - name: Install Node.js dependencies
      run: |
        cd openchronology.github.io/
        npm install
        npm install -g purescript spago
        cd ../

    # Runs a set of commands using the runners shell
    - name: Build
      run: |
        cd openchronology.github.io/
        ./build.sh
        cd ../

    - name: Commit
      run: |
        cd openchronology.github.io/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add . -A
        git commit -m "Auto build"

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.extract_branch.outputs.branch }}
